- hosts: localhost
  name: New System Setup
  gather_facts: true

  vars:
    home: "{{ lookup('env', 'HOME') }}"
    user: "{{ lookup('env', 'USER') }}"
    go_bin_path: '/opt/homebrew/bin' # Mac
    golangci_lint_version: '1.49.0'
    python_version: '3.11.5'
    node_version: '20'

  pre_tasks:
    - name: Update Homebrew on Mac
      community.general.homebrew:
        update_homebrew: true

  collections:
    - community.general.homebrew

  tasks:
    - import_tasks: tasks/mac-setup.yml
    - import_tasks: tasks/go-setup.yml
    - import_tasks: tasks/node-setup.yml
    - import_tasks: tasks/npm-packages.yml
    - import_tasks: tasks/lsp-setup.yml
    - import_tasks: tasks/debuggers.yml
    - import_tasks: tasks/dotfiles.yml
    - import_tasks: tasks/zsh-setup.yml
    - import_tasks: tasks/alacritty-build.yml
    - import_tasks: tasks/cargo-packages.yml
    - import_tasks: tasks/docker.yml
    - import_tasks: tasks/go-packages.yml
    - import_tasks: tasks/notes-setup.yml
    - import_tasks: tasks/nvim-setup.yml
    - import_tasks: tasks/pip-packages.yml
    - import_tasks: tasks/productivity-tools.yml
    - import_tasks: tasks/scripts-and-utils-setup.yml
    - import_tasks: tasks/tmux-setup.yml
    - import_tasks: tasks/zoom.yml
    # - import_tasks: tasks/update-all-packages.yml # Commented out as it should be run separately after initial setup
