- name: Install Docker Desktop
  ansible.builtin.command: 'brew install --cask docker'
  tags:
    - docker
    - mac-setup

- name: Add user to docker group
  become: true
  ansible.builtin.user:
    name: '{{ user }}'
    append: yes
    groups: docker
  tags:
    - docker
