- name: install zsh - MacOSX
  community.general.homebrew:
    name: zsh
    state: present
  tags: &tags_for_zsh_tasks ['wsl', 'install', 'productivity', 'dotfiles', 'zsh']
  when: ansible_distribution == 'MacOSX'


- name: change shell to zsh
  become: true
  #  shell: chsh -s $(chsh -l | grep zsh | sort -r | awk '(NR == 1){print $1}')
  shell: chsh -s $(which zsh) {{ user }}

- name: check if ~/.oh-my-zsh/ exists
  stat:
    path: '{{ home }}/.oh-my-zsh'
  register: oh_my_stats
  tags: *tags_for_zsh_tasks

- name: install oh my zsh
  ansible.builtin.git:
    repo: 'https://github.com/ohmyzsh/ohmyzsh.git'
    dest: '{{ home }}/.oh-my-zsh'
    depth: 1
  tags: *tags_for_zsh_tasks
  when: oh_my_stats.stat.exists == False


- name: install zsh-autosuggestions
  ansible.builtin.git:
    repo: 'https://github.com/zsh-users/zsh-autosuggestions.git' 
    dest: '{{ home }}/.oh-my-zsh/plugins/zsh-autosuggestions'
  tags: *tags_for_zsh_tasks
